;; This file is automatically generated by the multiple-cursors extension.
;; It keeps track of your preferences for running commands with multiple cursors.

(setq mc/cmds-to-run-for-all
      '(
        bbyac-expand-symbols
        evil-emacs-state
        evil-execute-in-god-state
        evil-next-line
        evil-normal-state
        smex
        sp-backward-delete-char
        sp-delete-char
        ))

(setq mc/cmds-to-run-once
      '(
        evil-delete-backward-char-and-join
        helm-confirm-and-exit-minibuffer
        ))
