;; This file is automatically generated by the multiple-cursors extension.
;; It keeps track of your preferences for running commands with multiple cursors.

(setq mc/cmds-to-run-for-all
      '(
	evil-execute-in-god-state
	smex
	))

(setq mc/cmds-to-run-once
      '(
	helm-confirm-and-exit-minibuffer
	))
